sudo: false

language: php

php:
    - '5.3'
    - '5.4'
    - '5.5'
    - '5.6'
    - '7.0'
    - hhvm

matrix:
    fast_finish: true
    allow_failures:
        - php: hhvm

cache:
    directories:
        - node_modules
        - $HOME/.composer/cache/files

before_install:
    - rm -rf "$HOME/.nvm"
    - git clone https://github.com/creationix/nvm.git "$HOME/.nvm"
    - source "$HOME/.nvm/nvm.sh"
    - nvm install node
    - npm config set progress false
    - npm install -g npm
    - composer self-update

install:
    - npm install
    - composer install --prefer-source

script:
    - npm run-script lint-travis
    - composer test-travis

after_success:
    - vendor/bin/coveralls --verbose

notifications:
    email: false

    slack:
        on_pull_requests: false
        on_start: never
        on_success: never
        on_failure: change
        rooms:
            - secure: X9XmgKYWLmCozvqs6qZWjWSZI1GPwhp94cBPuF9dfTDe8jXrv7cdtS7VB5Uwh9NaygsZ+l1znyeye4PPYxbcI2NmJKBYlYIwaGczjr9f2p/PfCzt5FJInEjS+cARPYPJLow5gcVNYiRCflkMwNuG1uR8HTs8dINVCEM/j2tMOi3K35G8sbqZjbrlBoTcF/oWmA6iSgwxYrEKR6DQ/oTLQic6n+nXFp+yA4DTrdmS8YhlWUyZre6Sq/rLI+tXF9444PGegeYlOtGGYhterU8cZ6Eqec33v8HqM97+a6trj+m52ITkuLOyayJ7RPN3P23w9KNWXRXre5+UjEksT4foRnhdkFklAGzNVpga+7P7PBSs8TdbnSN9zh89p15gBybEBsaBgcLKYx7hRCEhee/oubMyTl1KnjWNxx9GzfgJ06ctqmfPQHKAsZio+RMzetKzX2Dtl2ri3fw0gmVhSoCAipsFCa05W5ZFN/fRMh2XqDKVQmzcJwTSX6A2DujFSR5i8Ek3lUCuccpG9xb59n86mF5vtw/yUlmPx6P0d+5rzD/5UCYeW+a3yu7ohTLpXgbwuk4OHZJ2omD5xDHyFJM2GSk7nmCph2cJO4E+xGAxNgLLYa2oRRKTRNN8u/q55c1tcBpv4QT+srdi+x5kbLC1SYMgTMZzfC3zjQNmYOud0a0=
